#!/usr/bin/env bash
# configuring redirection 
sudo apt-get update -y
sudo apt-get install -y nginx
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name 107.21.38.255;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" | sudo tee /etc/nginx/sites-available/default;
sudo service nginx restart
