#!/usr/bin/env bash
# configuring redirection 
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name 107.21.38.255;
    location /redirect_me {
        return 301 https://intranet.alxswe.com/
    }
    location / {
        try_files $uri $uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/config
sudo service nginx restart
