#!/usr/bin/env bash
#configuring web 02

sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo "Hello World" | sudo tee /var/www/html/index.html >/dev/null
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/notFound.html

sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
    listen 80;
    listen [::]:80;

    error_page 404 /notFound.html;
    location = /notFound.html {
        root /var/www/html;
        internal;
    }  
    location / {
	root /var/www/html;
        add_header X-Served-By $HOSTNAME;
    }

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html; 
}
EOF

sudo service nginx restart
