#!/usr/bin/env bash
#configuring web 02
sudo apt-get update -y
sudo apt-get install -y nginx
sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;
    add_header X-served-By $HOSTNAME;

    error_page 404 /notFound.html;
    location = /notFound.html {
        root /var/www/html;
        internal;
    }  
    location / {
        return 404 "Ceci n'est pas une page";
    }

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html; 
}
EOF

echo "Ceci n'est pas une page" | sudo tee /var/www/html/notFound.html >/dev/null

sudo service nginx restart
