#!/usr/bin/env bash
# installing and configuring HA Proxy
apt-get update
apt-get install haproxy -y
echo "
frontend real-solution.tech
        bind *:80
        default_backend web_servers

backend web_servers
        mode http
        balance roundrobin
        server 398328-web-01 100.27.10.204:80 check
        server 398328-web-02 100.25.135.30:80 check
" > /etc/haproxy/haproxy.cfg
service haproxy restart
