#!/usr/bin/env bash
# thi print fizzbuzz using shell loop

i=1;
until [ $i -gt 100 ]; do 
	if  [ $(( i%3)) -eq 0 ]  && [ $((i%5)) -eq 0 ]; then 
		echo "FizzBuzz"
	elif [ $((i%3)) = 0 ]; then 
		echo "Fizz"
	elif [ $((i%5)) -eq 0 ]; then 
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
