#!/usr/bin/env bash
#this is a while loop , printing best school except for the 9th iteration

i=1;
while [ $i -le 10 ]; do 
	echo "Best School"
	if [ $i -eq 9 ]; then 
		echo "Hi"
	fi

	((i++))
done
