#!/usr/bin/env bash
#this is printing muintes and hours using while loop

hour=0;
min=1;
while [ $hour -le 12 ]; do 
	echo "Hour: $hour"
	while [ $min -le 59 ]; do 
		echo "$min"
		((min++))
	done
	min=1
	((hour++))
done
