#!/usr/bin/env bash
# configuring ssh client

Host ubuntu
        Hostname 100.27.10.204
        User ubuntu
        IdentityFIle ~/.ssh/school
        PasswordAuthentication no

Host ubuntu2
	Hostname 100.25.135.30
	User ubuntu
	IdentityFile ~/.ssh/school
	PasswordAuthentication no

Host LB_server
	Hostname 100.25.134.76
	User ubuntu
	IdentityFile ~/.ssh/school
	PasswordAuthentication no
